Syntax 6
Comment "PreSonus Quantum Thunderbolt Family"

# FIXME: name this file ${KBUILD_MODNAME}.conf at build time from the Makefile

SectionUseCase."HiFi" {
    Comment "Default"
    File "/${CardId}/HiFi.conf"
}