# HiFi.conf
# Specific configuration for PreSonus Quantum 4848

Define.INPUT_CHANNELS 48
Define.OUTPUT_CHANNELS 48
Define.RATE 48000

Include.common.File "/Quantum/Common.conf"

# --- OUTPUTS ---

SectionDevice."Out1" {
	Comment "Line OUT 1/2"
	Macro.pair.QuantumPlaybackPair {
		Priority 1000
		Channel0 0
		Channel1 1
	}
}

# ... 30 other line outputs

SectionDevice."Out17" {
	Comment "ADAT OUT 1/2"
	Macro.pair.QuantumPlaybackPair {
		Priority 700
		Channel0 32
		Channel1 33
	}
}

# ...up to 14 other ADAT outputs

# --- INPUTS ---

SectionDevice."In1" {
	Comment "Line In 1"
	Macro.channel.QuantumCaptureChannel {
		Priority 1000
		Channel 0
	}
}

SectionDevice."In2" {
	Comment "Line In 2"
	Macro.channel.QuantumCaptureChannel {
		Priority 1000
		Channel 1
	}
}

# ... 30 other line inputs

SectionDevice."In33" {
	Comment "ADAT Input 1"
	Macro.channel.QuantumCaptureChannel {
		Priority 500
		Channel 32
	}
}

SectionDevice."In34" {
	Comment "ADAT Input 2"
	Macro.channel.QuantumCaptureChannel {
		Priority 500
		Channel 33
	}
}

# ...up to 14 other ADAT inputs